version: 2.1
executors:
  docker_netcore:
    docker:
      - image: microsoft/dotnet:3.0-sdk
jobs:
  run_build:
    executor: docker_netcore
    steps:
      - checkout
      # - run:
      #     name: check dotnet version
      #     command: dotnet --version
      # - run:
      #     name: run dotnet sample app
      #     command: dotnet run
      - run:
          name: check what os it is
          command: uname -a
      - run:
          name: Install aws cli
          command: pip install --user --upgrade awscli
      - run:
          name: check aws cli version
          command: aws --version
  # deploy:
  #   executor: docker_netcore
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install awscli
  #         command:    

workflows:
  version: 2
  test_dotent:
    jobs:
      - run_build