version: 2.1
executors:
  docker_netcore:
    docker:
      - image: microsoft/dotnet:3.0-sdk
jobs:
  run_build:
    executor: docker_netcore
    steps:
      - checkout
      - run:
          name: check dotnet version
          command: dotnet --version
      - run:
          name: run dotnet sample app
          command: dotnet run
  deploy:
    executor: docker_netcore
    steps:
      - checkout
      - run:
          name: There's nothing in dotnet image; Install one by one
          command: |
            apt-get -y update
            apt-get -y install sudo
            # This image has python 2 installed
            sudo apt install -y python-pip
            pip install --user --upgrade awscli
      - run:
          name: check aws cli version
          command: |
            export PATH=~/.local/bin:$PATH
            aws --version
  test:
    executor: docker_netcore
    steps:
      - checkout
      - run:
          name: is this same instance with deploy?
          command: aws --version

workflows:
  version: 2
  test_dotent:
    jobs:
      - run_build